{{- include "indi-allsky.validateValues" . -}}
{{- if and .Values.mariadb.enabled (not .Values.mariadb.rootCredentials.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "indi-allsky.mariadbRootSecretName" . }}
  labels:
    {{- include "indi-allsky.labels" . | nindent 4 }}
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: {{ .Values.mariadb.rootCredentials.password | quote }}
{{- end }}
