{{- include "indi-allsky.validateValues" . -}}
{{- if not .Values.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "indi-allsky.envSecretName" . }}
  labels:
    {{- include "indi-allsky.labels" . | nindent 4 }}
type: Opaque
stringData:
  INDIALLSKY_FLASK_SECRET_KEY: {{ .Values.credentials.flaskSecretKey | quote }}
  INDIALLSKY_FLASK_PASSWORD_KEY: {{ .Values.credentials.flaskPasswordKey | quote }}
  MARIADB_PASSWORD: {{ .Values.credentials.mariadbPassword | quote }}
  {{- with .Values.oidc.clientSecret }}
  INDIALLSKY_OIDC_CLIENT_SECRET: {{ . | quote }}
  {{- end }}
  {{- with .Values.credentials.adminPassword }}
  INDIALLSKY_WEB_PASS: {{ . | quote }}
  {{- end }}
{{- end }}
