#!/usr/bin/env bash
# Failure diagnostics for the kind scenarios.
#
# Runs only when a scenario has already failed, so it never fails the job
# itself: every command is allowed to come up empty, because a cluster that
# broke early may genuinely have no pods to describe, and a diagnostics step
# that itself errors replaces the real failure in the log.
#
# It deliberately dumps object specs, events and container logs — never Secret
# contents. Object specs name Secrets and their keys; they do not carry values.
# Container logs are included because they are where the real cause usually is;
# the credential-leak assertions in the scenarios are what keep a credential
# from being in one to begin with, and every credential in these clusters is a
# per-run throwaway generated by e2e/install-release.sh.
set -uo pipefail

LOG_TAIL_LINES=300
EVENT_LIMIT=80

heading() {
    printf '\n===== %s =====\n' "$1"
}

heading "nodes"
kubectl get nodes --output wide || true
kubectl describe nodes | grep -E '^(Name:|Taints:|  Allocated|  cpu|  memory)' || true

heading "pods, all namespaces"
kubectl get pods --all-namespaces --output wide || true

heading "helm releases"
helm list --all-namespaces || true

for namespace in $(kubectl get namespaces --output jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' 2>/dev/null); do
    case "$namespace" in
        kube-system|kube-public|kube-node-lease|local-path-storage|default) continue ;;
    esac

    pods="$(kubectl --namespace "$namespace" get pods --output jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' 2>/dev/null)"
    [ -n "$pods" ] || continue

    heading "namespace ${namespace}: workloads"
    kubectl --namespace "$namespace" get all,pvc,networkpolicy --output wide || true

    heading "namespace ${namespace}: recent events"
    kubectl --namespace "$namespace" get events --sort-by=.lastTimestamp 2>/dev/null | tail -n "$EVENT_LIMIT" || true

    for pod in $pods; do
        heading "namespace ${namespace}: describe ${pod}"
        kubectl --namespace "$namespace" describe pod "$pod" || true

        containers="$(kubectl --namespace "$namespace" get pod "$pod" --output \
            'jsonpath={range .spec.initContainers[*]}{.name}{"\n"}{end}{range .spec.containers[*]}{.name}{"\n"}{end}' 2>/dev/null)"
        for container in $containers; do
            heading "namespace ${namespace}: logs ${pod}/${container}"
            kubectl --namespace "$namespace" logs "$pod" --container "$container" \
                --tail "$LOG_TAIL_LINES" || true
            # A restarted container's useful output is in the previous instance.
            kubectl --namespace "$namespace" logs "$pod" --container "$container" \
                --previous --tail "$LOG_TAIL_LINES" 2>/dev/null || true
        done
    done
done

exit 0
