#!/usr/bin/env bash
# Installs (or upgrades) one indi-allsky release into the kind cluster with
# run-generated credentials and digest-pinned images.
#
# DIGEST PINNING. The chart's published images are tagged `main`, and a tag is
# mutable: installing `:main` with IfNotPresent proves only that *some* build
# ran, not that the build carrying the code under review did. This script
# resolves each tag to its immutable manifest digest immediately before install,
# records the three digests in the job log (and in the GitHub step summary when
# one exists), and installs through image.digests.* so the whole release is
# pinned to exactly those bits for its lifetime — including any later
# `helm upgrade --reuse-values` a scenario performs.
#
# Resolution happens at run time rather than being committed to
# e2e/values-e2e.yaml on purpose. A committed digest starts rotting the moment
# images.yml republishes `:main`, and a release gate that silently tests
# last month's image is worse than one that tests a mutable tag, because it
# looks rigorous. The trade-off is stated plainly: on a pull request the images
# are main's, since images.yml publishes only from main.
#
# CREDENTIALS. Generated per cluster into a mode-0600 file under the state
# directory and never echoed. They are generated rather than tracked for the
# same reason the disposable MariaDB bench derives its fixture password at run
# time: a credential-shaped literal in a public repository is a liability even
# when it is worthless. The file is reused across calls so that the Fernet
# password key stays stable — rotating it between upgrades would make every
# encrypted configuration field unreadable, which is a fault this suite must
# not manufacture for itself.
set -Eeuo pipefail

SCRIPT_DIRECTORY="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=e2e/lib.sh
source "${SCRIPT_DIRECTORY}/lib.sh"

REPOSITORY_DIRECTORY="$(cd -- "${SCRIPT_DIRECTORY}/.." && pwd)"
CHART_DIRECTORY="${REPOSITORY_DIRECTORY}/charts/indi-allsky"
BASE_VALUES="${SCRIPT_DIRECTORY}/values-e2e.yaml"

STATE_DIRECTORY="${E2E_STATE_DIR:-${RUNNER_TEMP:-/tmp}/indi-allsky-e2e}"
CREDENTIALS_FILE="${STATE_DIRECTORY}/credentials-${RELEASE}.yaml"
DIGESTS_FILE="${STATE_DIRECTORY}/image-digests.yaml"

INSTALL_TIMEOUT="20m"
# Fernet requires a urlsafe-base64 encoding of exactly 32 bytes.
FERNET_KEY_BYTES=32
# Comfortably above usertool.py's eight-character floor.
GENERATED_SECRET_BYTES=24

IMAGE_NAMES=(indiserver daemon web)

mkdir -p -- "$STATE_DIRECTORY"
chmod 0700 -- "$STATE_DIRECTORY"


# --- credentials -------------------------------------------------------------

# base64url without padding: the character class is [A-Za-z0-9_-], which cannot
# introduce a URI delimiter into the rendered SQLAlchemy DSN or a YAML
# metacharacter into the values file.
generated_secret() {
    head -c "$GENERATED_SECRET_BYTES" /dev/urandom | base64 | tr '+/' '-_' | tr -d '='
}

# Padding is KEPT here: Fernet decodes the full 44-character form.
generated_fernet_key() {
    head -c "$FERNET_KEY_BYTES" /dev/urandom | base64 | tr '+/' '-_'
}

if [ ! -f "$CREDENTIALS_FILE" ]; then
    umask 077
    cat >"$CREDENTIALS_FILE" <<CREDENTIALS
# Generated by e2e/install-release.sh for release ${RELEASE}. Throwaway values
# for one disposable kind cluster; never printed, never committed.
credentials:
  flaskSecretKey: "$(generated_secret)"
  flaskPasswordKey: "$(generated_fernet_key)"
  mariadbPassword: "$(generated_secret)"
  adminPassword: "$(generated_secret)"
mariadb:
  rootCredentials:
    password: "$(generated_secret)"
CREDENTIALS
    umask 022
    note "generated throwaway credentials for release ${RELEASE} ($(wc -c <"$CREDENTIALS_FILE" | tr -d ' ') bytes)"
fi
test "$(stat -c '%a' "$CREDENTIALS_FILE")" = "600" \
    || fail "the generated credentials file is not mode 0600"


# --- image digests -----------------------------------------------------------

# Anonymous Docker registry v2 token flow. Deliberately curl rather than a
# docker/crane/skopeo dependency: nothing here needs a daemon, a builder, or an
# extra pinned binary, and the digest that comes back is the registry's own
# content address rather than something re-derived locally.
resolve_manifest_digest() {  # $1 = registry host, $2 = repository, $3 = tag
    local host="$1" repository="$2" tag="$3" token
    token="$(
        curl --silent --show-error --fail --location \
            "https://${host}/token?scope=repository:${repository}:pull&service=${host}" \
            | jq -r '.token // empty'
    )"
    test -n "$token" || return 1
    curl --silent --show-error --fail --location --head \
        --header "Authorization: Bearer ${token}" \
        --header 'Accept: application/vnd.oci.image.index.v1+json' \
        --header 'Accept: application/vnd.docker.distribution.manifest.list.v2+json' \
        --header 'Accept: application/vnd.oci.image.manifest.v1+json' \
        --header 'Accept: application/vnd.docker.distribution.manifest.v2+json' \
        "https://${host}/v2/${repository}/manifests/${tag}" \
        | tr -d '\r' \
        | sed -n 's/^[Dd]ocker-[Cc]ontent-[Dd]igest: //p' \
        | tail -1
}

if [ ! -f "$DIGESTS_FILE" ]; then
    registry="$(helm show values "$CHART_DIRECTORY" | yq -r '.image.registry')"
    tag="${E2E_IMAGE_TAG:-main}"
    registry_host="${registry%%/*}"
    registry_path="${registry#*/}"
    case "$registry_host" in
        *.*|*:*) ;;
        *) fail "the digest resolver expects image.registry to begin with a registry host (got ${registry})" ;;
    esac

    printf 'resolving image digests for %s/indi-allsky-{%s}:%s\n' \
        "$registry" "$(IFS=,; echo "${IMAGE_NAMES[*]}")" "$tag"
    {
        echo "# Resolved by e2e/install-release.sh immediately before install."
        echo "image:"
        echo "  digests:"
    } >"$DIGESTS_FILE"
    for name in "${IMAGE_NAMES[@]}"; do
        repository="${registry_path}/indi-allsky-${name}"
        digest="$(resolve_manifest_digest "$registry_host" "$repository" "$tag")" \
            || fail "could not resolve ${registry}/indi-allsky-${name}:${tag} — is the GHCR package still public?"
        case "$digest" in
            sha256:*) ;;
            *) fail "the registry returned no manifest digest for ${registry}/indi-allsky-${name}:${tag}" ;;
        esac
        printf '    %s: "%s"\n' "$name" "$digest" >>"$DIGESTS_FILE"
        printf '  %-10s %s\n' "${name}:" "$digest"
        if [ -n "${GITHUB_STEP_SUMMARY:-}" ]; then
            # The backticks are Markdown for the step summary, not command
            # substitution — hence the single quotes and the directive.
            # shellcheck disable=SC2016
            printf -- '- `%s/indi-allsky-%s:%s` -> `%s`\n' \
                "$registry" "$name" "$tag" "$digest" >>"$GITHUB_STEP_SUMMARY"
        fi
    done
fi


# --- install -----------------------------------------------------------------

kubectl create namespace "$NAMESPACE" --dry-run=client --output yaml | kubectl apply --filename -

helm upgrade --install "$RELEASE" "$CHART_DIRECTORY" \
    --namespace "$NAMESPACE" \
    --values "$BASE_VALUES" \
    --values "$CREDENTIALS_FILE" \
    --values "$DIGESTS_FILE" \
    --timeout "$INSTALL_TIMEOUT" \
    "$@"

pass "release ${RELEASE} installed in namespace ${NAMESPACE} with digest-pinned images"
