#!/bin/bash
# Schema and first-run bootstrap for indi-allsky, part two of two.
#
# Runs as the child of db-maintenance-lock.sh, so every command here executes
# while this pod holds the shared database-maintenance advisory lock. It is not
# an entrypoint: migrate.sh execs the lock supervisor, which execs this.
#
# THE SAFETY PROPERTY (issue #22)
#
# No schema-mutating command runs before a fresh, verified dump has been
# atomically published — not `flask db upgrade head`, not an autogenerated
# revision. The only exceptions are the explicit INDIALLSKY_PRE_MIGRATE_DUMP
# =false escape hatch, and the case where two non-mutating probes together
# prove there is nothing to apply. Every probe fails closed: if it cannot
# answer, the dump is taken.
#
# THE COMMIT POINT
#
# The applied-overlay checksum sentinel is written last, atomically, only after
# migration, bootstrap, overlay application and optional admin seeding have all
# succeeded. No failure path touches it, so the edge pod's version barrier can
# never be released by a run that did not finish.
#
# Like render-flask-config.sh, this script must never gain `set -x`: it handles
# the database password and writes files derived from the decrypted config
# dump.

set -o errexit
set -o nounset
# pipefail is load-bearing, not boilerplate: the pre-migration backup is
# `mariadb-dump ... | gzip > file`, and without it a mariadb-dump that dies
# mid-stream still leaves the pipeline exit status at gzip's 0 — the script
# would go on to mutate the schema believing it had a backup.
set -o pipefail

# Every file this script creates carries decrypted configuration, database
# contents, or both. 077 from the first byte, so nothing is briefly readable
# between creat() and chmod().
umask 077

ALLSKY_DIRECTORY="/home/allsky/indi-allsky"
ALLSKY_ETC="/etc/indi-allsky"
FLASK_CONFIG="${ALLSKY_ETC}/flask.json"

# Kept for images run outside this chart. The chart always sets
# INDIALLSKY_BACKUP_DIR to the persistent sibling outside the web docroot.
DEFAULT_BACKUP_DIR="/var/www/html/allsky/.state/backups"

# Final-name prefix for this producer. The scheduled backup CronJob owns a
# different one; neither prefix's retention may ever see the other's files.
PRE_MIGRATE_DUMP_PREFIX="pre-migrate"
DEFAULT_PRE_MIGRATE_DUMP_KEEP=8

# usertool.py's own constraint (misc/usertool.py:109).
MIN_WEB_PASS_LENGTH=8

# Fresh database has 0 users; after `config.py bootstrap` there is exactly one
# — the internal 'system' account it creates. Anything above that means a real
# operator account already exists and must not be re-seeded.
MAX_USER_COUNT_FOR_SEED=1

# The chart's checksum contract: lowercase hex sha256 of the canonical overlay
# bytes, and exactly that plus one newline in the sentinel.
OVERLAY_CHECKSUM_PATTERN='^[0-9a-f]{64}$'
SENTINEL_FILE_MODE="0600"

# shellcheck disable=SC1091  # installed alongside this script by the Dockerfile; not resolvable at lint time
source /home/allsky/validators.sh
# shellcheck disable=SC1091  # installed alongside this script by the Dockerfile; not resolvable at lint time
source /home/allsky/db-connection.sh
# shellcheck disable=SC1091  # installed alongside this script by the Dockerfile; not resolvable at lint time
source /home/allsky/dump-publish.sh

db_connection_init

# flask / config.py / usertool.py resolve the application from ./app.py in the
# checkout — upstream ships no FLASK_APP — so the working directory is part of
# the contract, not a convenience.
cd "$ALLSKY_DIRECTORY"

# shellcheck disable=SC1091  # created by upstream's Dockerfile at image build time; not in this repo
source /home/allsky/venv/bin/activate


# --- temporary-file lifecycle -----------------------------------------------
#
# All four hold either decrypted third-party credentials or an unpublished
# artifact, so they are removed on every exit path including handled signals.
TEMPORARY_CONFIG_DUMP=""
TEMPORARY_MERGED_CONFIG=""
OVERLAY_SNAPSHOT=""
TEMPORARY_SENTINEL=""

cleanup() {
    dump_cleanup
    rm -f -- \
        ${TEMPORARY_CONFIG_DUMP:+"$TEMPORARY_CONFIG_DUMP"} \
        ${TEMPORARY_MERGED_CONFIG:+"$TEMPORARY_MERGED_CONFIG"} \
        ${OVERLAY_SNAPSHOT:+"$OVERLAY_SNAPSHOT"} \
        ${TEMPORARY_SENTINEL:+"$TEMPORARY_SENTINEL"}
}
trap cleanup EXIT INT TERM HUP


# --- effective paths --------------------------------------------------------
#
# Read back what render-flask-config.sh decided, so the defaults exist in
# exactly one place. migrate.sh has already created the image folder and the
# migration folder's parent.
MIGRATION_FOLDER="$(jq -er '.MIGRATION_FOLDER' "$FLASK_CONFIG")"
IMAGE_FOLDER="$(jq -er '.INDI_ALLSKY_IMAGE_FOLDER' "$FLASK_CONFIG")"

dump_require_safe_directory INDIALLSKY_MIGRATION_FOLDER "$(dirname "$MIGRATION_FOLDER")"


# --- overlay snapshot -------------------------------------------------------
#
# Kubernetes updates a projected ConfigMap file in place while the pod runs, so
# reading the overlay twice — once to verify its checksum, once to merge it —
# is a genuine time-of-check/time-of-use race: an edit landing between the two
# reads would be applied under the previous rollout's checksum, and the
# sentinel would then certify bytes that were never applied.
#
# The projection is therefore read EXACTLY ONCE into a private snapshot, and
# every later step — the checksum comparison, the merge, and the sentinel —
# uses only that immutable copy. A projection edited after this read simply
# fails the comparison, because the expected checksum comes from this pod's own
# environment and rolls with the Deployment.
OVERLAY_SOURCE="${INDIALLSKY_CONFIG_OVERLAY:-}"
EXPECTED_OVERLAY_CHECKSUM="${INDIALLSKY_CONFIG_OVERLAY_SHA256:-}"
APPLIED_SENTINEL="${INDIALLSKY_CONFIG_OVERLAY_APPLIED_SENTINEL:-}"

if [ -n "$EXPECTED_OVERLAY_CHECKSUM" ]; then
    if ! [[ "$EXPECTED_OVERLAY_CHECKSUM" =~ $OVERLAY_CHECKSUM_PATTERN ]]; then
        echo "FATAL: INDIALLSKY_CONFIG_OVERLAY_SHA256 must be 64 lowercase hex characters (got ${#EXPECTED_OVERLAY_CHECKSUM} bytes)" >&2
        exit 1
    fi
    if [ -z "$OVERLAY_SOURCE" ]; then
        echo "FATAL: INDIALLSKY_CONFIG_OVERLAY_SHA256 is set but INDIALLSKY_CONFIG_OVERLAY names no file" >&2
        exit 1
    fi
fi

if [ -n "$OVERLAY_SOURCE" ] && [ -f "$OVERLAY_SOURCE" ]; then
    OVERLAY_SNAPSHOT="$(mktemp "${ALLSKY_ETC}/.config-overlay-snapshot.XXXXXX.json")"
    cat -- "$OVERLAY_SOURCE" >"$OVERLAY_SNAPSHOT"
    chmod 0600 "$OVERLAY_SNAPSHOT"

    if [ -n "$EXPECTED_OVERLAY_CHECKSUM" ]; then
        SNAPSHOT_CHECKSUM="$(sha256sum <"$OVERLAY_SNAPSHOT" | cut -d' ' -f1)"
        if [ "$SNAPSHOT_CHECKSUM" != "$EXPECTED_OVERLAY_CHECKSUM" ]; then
            echo "FATAL: projected config overlay does not match INDIALLSKY_CONFIG_OVERLAY_SHA256 — the ConfigMap and this pod's environment are from different rollouts" >&2
            exit 1
        fi
        echo "Config overlay snapshot matches the expected checksum"
    fi

    # Parsed before use so a malformed overlay fails here rather than inside
    # the merge, where jq's error names a temporary path instead of the cause.
    jq -e . "$OVERLAY_SNAPSHOT" >/dev/null
elif [ -n "$EXPECTED_OVERLAY_CHECKSUM" ]; then
    echo "FATAL: config overlay ${OVERLAY_SOURCE} is missing — mount the overlay ConfigMap on its own volume" >&2
    exit 1
fi


# --- migration history ------------------------------------------------------
#
# Test the artifact, not the directory: MIGRATION_FOLDER lives on the shared
# data volume, and a subPath mount (or a previous run that failed between
# mkdir and init) leaves an existing-but-empty directory. A `-d` test would
# skip init there and then die at `db upgrade`.
if [[ ! -f "${MIGRATION_FOLDER}/env.py" ]]; then
    echo "No migration history at ${MIGRATION_FOLDER}; initialising"
    flask db init
fi

dump_require_safe_directory INDIALLSKY_MIGRATION_FOLDER "$MIGRATION_FOLDER"

# The Alembic tree is executed, not merely read: env.py and every revision are
# imported by `flask db upgrade`. Anything in it that another uid could rewrite
# is arbitrary code execution inside this container. Same-uid tampering remains
# possible until issue #9 ships reviewed revisions inside the image; this
# closes the cross-uid half.
if [ -n "$(find "$MIGRATION_FOLDER" -maxdepth 2 \
        \( ! -user "$DUMP_EXPECTED_UID" -o -perm /022 \) -print -quit)" ]; then
    echo "FATAL: ${MIGRATION_FOLDER} contains entries not owned by uid ${DUMP_EXPECTED_UID} or writable by group/other" >&2
    exit 1
fi


# --- is there any schema work to do? ----------------------------------------
#
# Both probes are non-mutating and both fail CLOSED: an unexpected status or
# unparseable output returns "yes, there is work", so the dump is taken. That
# direction matters — the failure this guard exists to prevent is mutating a
# schema with no fresh recovery artifact, never taking a dump that turned out
# to be unnecessary.
alembic_revision_ids() {  # reads `flask db <subcommand>` output on stdin
    sed -n 's/^\([0-9a-f][0-9a-f]*\).*/\1/p' | sort | tr '\n' ' '
}

schema_work_pending() {
    local current heads
    current="$(flask db current 2>/dev/null)" || return 0
    heads="$(flask db heads 2>/dev/null)" || return 0
    current="$(printf '%s\n' "$current" | alembic_revision_ids)"
    heads="$(printf '%s\n' "$heads" | alembic_revision_ids)"
    # Behind the committed revisions: `upgrade` has something to apply.
    [ "$current" == "$heads" ] || return 0
    # Up to date, but the models may still have drifted from the live schema,
    # which is what the autogenerate branch below answers.
    flask db check >/dev/null 2>&1 || return 0
    return 1
}


# --- pre-migration dump -----------------------------------------------------
#
# Strict true|false. A loose `== "true"` test treats True, TRUE, 1, yes and
# every typo as "skip the dump", so a mistyped value would silently discard the
# backup and then mutate the schema, at exit 0 — this file's safety property
# inverted. Only the length is reported, never the value.
PRE_MIGRATE_DUMP="$(require_bool INDIALLSKY_PRE_MIGRATE_DUMP "${INDIALLSKY_PRE_MIGRATE_DUMP:-true}")"

if schema_work_pending; then
    echo "Schema work is pending"
    if [ "$PRE_MIGRATE_DUMP" == "true" ]; then
        DUMP_DIR="${INDIALLSKY_BACKUP_DIR:-$DEFAULT_BACKUP_DIR}"
        PRE_MIGRATE_DUMP_KEEP="${INDIALLSKY_PRE_MIGRATE_DUMP_KEEP:-$DEFAULT_PRE_MIGRATE_DUMP_KEEP}"

        # A retention of 0 would prune the dump taken moments ago, immediately
        # before the schema is mutated — the safety property inverted. A
        # non-numeric value would make the arithmetic silently mean 0.
        case "$PRE_MIGRATE_DUMP_KEEP" in
            ''|*[!0-9]*)
                echo "FATAL: INDIALLSKY_PRE_MIGRATE_DUMP_KEEP must be a whole number (got ${#PRE_MIGRATE_DUMP_KEEP} bytes)" >&2
                exit 1 ;;
        esac
        if [ "$PRE_MIGRATE_DUMP_KEEP" -lt 1 ]; then
            echo "FATAL: INDIALLSKY_PRE_MIGRATE_DUMP_KEEP must be at least 1 — retaining zero dumps would delete the backup this migration depends on. To skip the dump entirely, set INDIALLSKY_PRE_MIGRATE_DUMP=false." >&2
            exit 1
        fi

        dump_require_private_directory INDIALLSKY_BACKUP_DIR "$DUMP_DIR"
        publish_verified_dump "$DUMP_DIR" "$PRE_MIGRATE_DUMP_PREFIX"
        prune_published_dumps "$DUMP_DIR" "$PRE_MIGRATE_DUMP_PREFIX" "$PRE_MIGRATE_DUMP_KEEP"
    else
        # Deliberate, explicit, and never the default. Appropriate only for an
        # external database whose backups a DBA already manages.
        echo "INDIALLSKY_PRE_MIGRATE_DUMP=false; proceeding without a pre-migration dump"
    fi
else
    echo "Schema matches models and committed revisions; no pre-migration dump needed"
fi


# --- apply the schema -------------------------------------------------------
#
# Only now, with a published recovery artifact behind us. `upgrade` first, then
# `check`: on a database that is merely behind the committed revisions, `check`
# reports a difference that `upgrade` — not a new autogenerated revision — is
# the correct answer to.
flask db upgrade head

if flask db check; then
    echo "Schema matches models; no migration needed"
else
    # v1 compromise: generating revisions at runtime means the schema history
    # is produced on the operator's cluster rather than reviewed in CI.
    # CI-committed revisions replace this block and are a hard prerequisite
    # for the first UPSTREAM_VERSION bump — tracked in issue #9. Until then
    # the dump published above is what makes an unreviewed migration
    # recoverable.
    echo "Model changes detected; generating guarded migration"
    flask db revision --autogenerate -m "runtime autogenerate $(date +%Y-%m-%dT%H:%M:%S%z)"
    flask db upgrade head
fi


# --- initial configuration --------------------------------------------------
#
# `config.py bootstrap` exits 1 in two very different situations: when a
# configuration already exists (indi_allsky/config.py:1471, the normal
# second-run case) and when it genuinely failed. A bare `|| true` cannot tell
# them apart and would let a broken deployment continue. Probing with
# `dumpfile` distinguishes them: it succeeds only when a committed config row
# is readable. Its output is discarded to /dev/null because a config dump
# contains third-party credentials decrypted.
if ! ./config.py bootstrap --image_folder "$IMAGE_FOLDER"; then
    ./config.py dumpfile -o /dev/null >/dev/null 2>&1 \
        || { echo "FATAL: config.py bootstrap failed and no existing config is readable" >&2; exit 1; }
    echo "Configuration already initialized; continuing"
fi


# --- config overlay ---------------------------------------------------------
#
# `jq -s '.[0] * .[1]'` merges objects recursively but REPLACES arrays
# wholesale, and cannot remove a key. The right-hand operand is the immutable
# snapshot taken above, never the live projection.
if [ -n "$OVERLAY_SNAPSHOT" ]; then
    echo "Applying config overlay from the verified snapshot of ${OVERLAY_SOURCE}"
    TEMPORARY_CONFIG_DUMP="$(mktemp --suffix=.json)"
    TEMPORARY_MERGED_CONFIG="$(mktemp --suffix=.json)"
    ./config.py dump >"$TEMPORARY_CONFIG_DUMP"
    jq -s '.[0] * .[1]' "$TEMPORARY_CONFIG_DUMP" "$OVERLAY_SNAPSHOT" >"$TEMPORARY_MERGED_CONFIG"
    ./config.py load -c "$TEMPORARY_MERGED_CONFIG" --force
fi


# --- admin account ----------------------------------------------------------
#
# usertool.py validates interactively: an empty or short password, a username
# with spaces, or a malformed email all drop it into input()/getpass() rather
# than failing. In an initContainer with no tty that is a hang or an EOFError
# traceback, neither of which tells the operator what was wrong. Check the
# same constraints up front (misc/usertool.py:44, :109, :132) and redirect
# stdin from /dev/null so any remaining prompt fails immediately instead of
# blocking the pod.
#
# LOCAL_AUTH_ENABLE is not re-validated here: render-flask-config.sh already
# put it through require_bool and aborted before this script got this far.
#
# The credential guards live INSIDE the seeding branch, not above it. Two
# reviewers reached this placement from opposite directions, so the
# reasoning is recorded here rather than re-litigated:
#
#   * Hoisting them earlier would fail a credential typo in ~1s instead of
#     ~7s, before any schema work — a real diagnosis-speed gain.
#   * But whether seeding applies at all is unknowable until the database is
#     up and counted. On an already-seeded deployment whose bootstrap secret
#     has since been rotated away, hoisted guards turn "2 accounts exist;
#     not seeding" into a FATAL, bricking the initContainer on every restart
#     and silently making INDIALLSKY_WEB_PASS permanently required — a
#     contract change nobody agreed to.
#
# Validation may therefore only gate the seeding *action*, which is what this
# ordering does. The diagnosis-speed loss is bounded by the DB wait and is
# the cheaper of the two costs.
if [ "${INDIALLSKY_LOCAL_AUTH_ENABLE:-true}" == "true" ] && [ -n "${INDIALLSKY_WEB_USER:-}" ]; then
    USER_COUNT=$(./config.py user_count)

    if [ "$USER_COUNT" -le "$MAX_USER_COUNT_FOR_SEED" ]; then
        WEB_PASS="${INDIALLSKY_WEB_PASS:-}"
        WEB_EMAIL="${INDIALLSKY_WEB_EMAIL:-admin@example.com}"

        case "$INDIALLSKY_WEB_USER" in *[[:space:]]*)
            echo "FATAL: INDIALLSKY_WEB_USER must not contain spaces" >&2; exit 1 ;;
        esac
        if [ "${#WEB_PASS}" -lt "$MIN_WEB_PASS_LENGTH" ]; then
            echo "FATAL: INDIALLSKY_WEB_PASS must be at least ${MIN_WEB_PASS_LENGTH} characters" >&2
            exit 1
        fi
        if ! printf '%s' "$WEB_EMAIL" | grep -Eq '^[^@]+@[^@]+\.[^@]+$'; then
            echo "FATAL: INDIALLSKY_WEB_EMAIL is not a valid address" >&2
            exit 1
        fi

        echo "Seeding admin account ${INDIALLSKY_WEB_USER}"
        ./misc/usertool.py adduser -u "$INDIALLSKY_WEB_USER" -p "$WEB_PASS" \
            -f "${INDIALLSKY_WEB_NAME:-Admin}" -e "$WEB_EMAIL" </dev/null
        ./misc/usertool.py setadmin -u "$INDIALLSKY_WEB_USER" </dev/null
    else
        echo "${USER_COUNT} accounts already exist; not seeding"
    fi
fi


# --- applied-overlay sentinel: the commit point -----------------------------
#
# Last, and only here. Everything above has succeeded, so the exact checksum of
# the overlay this rollout applied can now be published for the edge pod's
# version barrier. Staged in the destination directory so the install is a
# same-filesystem rename, fsynced before that rename so the sentinel can never
# name a checksum whose bytes are not durable, and never written on any failure
# path — an unchanged sentinel keeps the edge pod waiting, which is the
# fail-safe direction.
#
# Rename, not the hard link the dumps use: this file must REPLACE its
# predecessor, whereas a dump must never replace anything.
if [ -n "$EXPECTED_OVERLAY_CHECKSUM" ] && [ -n "$APPLIED_SENTINEL" ]; then
    SENTINEL_DIRECTORY="$(dirname "$APPLIED_SENTINEL")"
    mkdir -p -- "$SENTINEL_DIRECTORY" || {
        echo "FATAL: cannot create ${SENTINEL_DIRECTORY} — the data volume must be writable by uid ${DUMP_EXPECTED_UID}" >&2
        exit 1
    }
    TEMPORARY_SENTINEL="$(mktemp "${SENTINEL_DIRECTORY}/.config-overlay.applied.XXXXXX")"
    printf '%s\n' "$EXPECTED_OVERLAY_CHECKSUM" >"$TEMPORARY_SENTINEL"
    chmod "$SENTINEL_FILE_MODE" "$TEMPORARY_SENTINEL"
    dump_fsync "$TEMPORARY_SENTINEL"
    mv -f -- "$TEMPORARY_SENTINEL" "$APPLIED_SENTINEL"
    TEMPORARY_SENTINEL=""
    dump_fsync "$SENTINEL_DIRECTORY"
    echo "Published applied-overlay checksum sentinel ${APPLIED_SENTINEL}"
fi

echo "Migration and bootstrap complete"
